# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PDF Archiver
author: Julian Kahnert
email: pdf-archiver@juliankahnert.de
description: Scan it. Tag it. Find it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "pdf-archiver.io"
twitter_username: jekyllrb
github_username:  jekyll
discord_url: 'https://discord.gg/H3k47WE'
github_url: 'https://github.com/PDF-Archiver/PDF-Archiver'
faq_url: '/faq'
support_email: 'support@pdf-archiver.io'
faq_email: 'faq@pdf-archiver.io'
feature_requests_email: 'feature-request@pdf-archiver.io'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
  - jekyll-email-protect
font-awesome:
  assets: true
languages: ["en", "de"]
exclude_from_localizations: ["assets",]
collections:
  changelog:
    output: false
  faq:
    output: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
